/* eslint-disable */
// Generated by Wrangler
declare namespace Cloudflare {
	interface Env {
		ASSETS: R2Bucket; // Overridden by api-worker, or Fetcher for pages
		API: Fetcher;
		GATEWAY: Fetcher;
		KV: KVNamespace;
		CONTROL_LOGS: KVNamespace;
		DB: D1Database;
		AI: any;
		STATE: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
