cloudflare:
  account_name: goldshore-account
  zone: goldshore.ai

  dns:
    records:
      - name: "goldshore.ai"
        type: CNAME
        content: "astro-gs-web.pages.dev"
        proxied: true

      - name: "admin"
        type: CNAME
        content: "astro-gs-admin.pages.dev"
        proxied: true

      - name: "api"
        type: CNAME
        content: "astro-gs-api.example.workers.dev"
        proxied: true

      - name: "gw"
        type: CNAME
        content: "astro-gs-gateway.example.workers.dev"
        proxied: true

      - name: "preview"
        type: CNAME
        content: "astro-gs-web.pages.dev"
        proxied: false

      - name: "admin-preview"
        type: CNAME
        content: "astro-gs-admin.pages.dev"
        proxied: false

      - name: "api-preview"
        type: CNAME
        content: "astro-gs-api.example.workers.dev"
        proxied: false

      - name: "gw-preview"
        type: CNAME
        content: "astro-gs-gateway.example.workers.dev"
        proxied: false

  pages:
    projects:
      - name: "astro-gs-web"
        repo: "astro-goldshore"
        root_dir: "/" # Run from repo root for monorepo support
        production_branch: "main"
        build_command: "pnpm --filter @goldshore/web build"
        output_dir: "apps/web/dist"
        custom_domains:
          - "goldshore.ai"
          - "preview.goldshore.ai"

      - name: "astro-gs-admin"
        repo: "astro-goldshore"
        root_dir: "/" # Run from repo root for monorepo support
        production_branch: "main"
        build_command: "pnpm --filter @goldshore/admin build"
        output_dir: "apps/admin/dist"
        custom_domains:
          - "admin.goldshore.ai"
          - "admin-preview.goldshore.ai"

  workers:
    services:
      - name: "astro-gs-api"
        script_path: "apps/api-worker/dist/index.js"
        routes:
          - pattern: "api.goldshore.ai/*"
          - pattern: "api-preview.goldshore.ai/*"
        bindings:
          kv:
            - name: "API_KV"
              namespace: "goldshore-api-kv"
          d1:
            - name: "DB"
              database_name: "goldshore-api-db"
          r2:
            - name: "ASSETS"
              bucket_name: "goldshore-api-assets"
          ai:
            - name: "AI"
              gateway: "goldshore-ai-gateway"

      - name: "astro-gs-gateway"
        script_path: "apps/gateway/dist/index.js"
        routes:
          - pattern: "gw.goldshore.ai/*"
          - pattern: "gw-preview.goldshore.ai/*"
        bindings:
          services:
            - binding: "API"
              service: "astro-gs-api"
              environment: "production"
          kv:
            - name: "GATEWAY_KV"
              namespace: "goldshore-gw-kv"

  email:
    routing:
      catch_all:
        enabled: true
        destination: "inbox@goldshore.ai"
      addresses:
        - address: "ops@goldshore.ai"
          destination: "your.personal.email@example.com"
        - address: "support@goldshore.ai"
          destination: "your.personal.email@example.com"
